FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y gcc-multilib g++ cmake
RUN apt-get install -y libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libfreetype-dev libfreetype6 libfreetype6-dev # SFML deps
