name: Doxygen Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  files_changed:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.check_changed_files.outputs.files_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        uses: tj-actions/changed-files@v35
        id: changed_files

      - name: Check changed files
        id: check_changed_files
        run: |
          for file in ${{ steps.changed_files.outputs.all_modified_files }}; do
            echo ""$file" was changed"
            if [ ! -z "$(echo $file | grep -E "*.cpp|*.hpp")" ]; then
              echo ::set-output name=files_changed::true
              break
            fi
          done;

  doxygen:
    needs: files_changed
    if: always() && (needs.files_changed.outputs.files_changed == 'True' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: "./"
          doxyfile-path: "./docs/Doxyfile"
          enable-latex: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/doc/html
