name: Installer Action

on:
  push:
    branches:
      - 'v*'
  workflow_dispatch:

jobs:
  linux_installer:
    runs-on: ubuntu-latest
    container: docker://alwyn974/rtype-build:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache libraries
        id: cache-libraries
        uses: actions/cache@v3
        with:
          path: ./build/_deps
          key: ${{ runner.os }}-libraries-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure CMake (Shared)
        shell: bash
        run: cmake -B ./build -S . -DSATURNITY_CPACK=ON -DBUILD_SHARED_LIBS=ON

      - name: Build Shared Release
        shell: bash
        run: cmake --build ./build --config Release -j`nproc`

      - name: Create Shared Installer
        shell: bash
        working-directory: ./build
        run: cpack -G "DEB;RPM"

      - name: Configure CMake (Static)
        shell: bash
        run: cmake -B ./build -S . -DSATURNITY_CPACK=ON -DBUILD_SHARED_LIBS=OFF

      - name: Build Static Release
        shell: bash
        run: cmake --build ./build --config Release -j`nproc`

      - name: Create Static Installer
        shell: bash
        working-directory: ./build
        run: cpack -G "DEB;RPM"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux_installer
          path: |
            build/Saturnity*.deb
            build/Saturnity*.rpm
            build/*.sha256

  windows_installer:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache libraries
        id: cache-libraries
        uses: actions/cache@v3
        with:
          path: ./build/_deps
          key: ${{ runner.os }}-libraries-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure CMake (Shared)
        shell: bash
        run: cmake -B ./build -S . -DSATURNITY_CPACK=ON -DBUILD_SHARED_LIBS=ON

      - name: Build Shared Release
        shell: pwsh
        run: cmake --build ./build --config Release -j"$env:NUMBER_OF_PROCESSORS"

      - name: Create Shared Installer
        shell: pwsh
        working-directory: ./build
        run: cpack -G "NSIS"

      - name: Configure CMake (Static)
        shell: bash
        run: cmake -B ./build -S . -DSATURNITY_CPACK=ON -DBUILD_SHARED_LIBS=OFF

      - name: Build Static Release
        shell: pwsh
        run: cmake --build ./build --config Release -j"$env:NUMBER_OF_PROCESSORS"

      - name: Create Static Installer
        shell: pwsh
        working-directory: ./build
        run: cpack -G "NSIS"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows_installer
          path: |
            build/Saturnity*.exe
            build/*.sha256

  create_release:
    needs:
      - linux_installer
      - windows_installer
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        id: download_artifacts
        uses: actions/download-artifact@v3

      - name: Create body file
        run: |
          echo "Automated release of $GITHUB_REF_NAME" > body.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: |
            ${{ steps.download_artifacts.outputs.download-path }}/linux_installer/Saturnity*.deb
            ${{ steps.download_artifacts.outputs.download-path }}/linux_installer/Saturnity*.rpm
            ${{ steps.download_artifacts.outputs.download-path }}/linux_installer/*.sha256
            ${{ steps.download_artifacts.outputs.download-path }}/windows_installer/Saturnity*.exe
            ${{ steps.download_artifacts.outputs.download-path }}/windows_installer/*.sha256
          bodyFile: body.md
          generateReleaseNotes: true
          tag: ${{ github.ref }}
